name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
          
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi
          
      - name: Install Pico SDK
        run: |
          git clone https://github.com/raspberrypi/pico-sdk.git
          cd pico-sdk
          git submodule update --init --recursive
          cd ..

      - name: Build
        run: |
          export PICO_SDK_PATH=../../pico-sdk
          export PATH=$PICO_SDK_PATH/tools:$PATH
          cd C-Code
          mkdir build
          cd build
          cmake -DPICO_BOARD=pico ..
          make

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          path: C-Code/build/*.uf2
